---
deployment:
    tasks:
      - export DEPLOYPATH="/home/zzaharic/public_html"
      - export SBOXPATH="/home/zzaharic/repositories"
      - echo "[INFO] Initiate Deployment to $DEPLOY_PATH..."
      - echo "$PWD"