---
deployment:
    tasks:
      - export DEPLOYPATH="/home/zzaharic/public_html"
      - export SBOXPATH="$PWD"
      - echo "[INFO] Initiate Deployment to $DEPLOY_PATH..."
      - /bin/cp -rf $SBOXPATH/* $DEPLOYPATH