---
deployment:
    tasks:
      - export DEPLOYPATH="/home/zzaharic/public_html"
      - echo "[INFO] removing previous deployment directory..."
      - /bin/rm -rf $DEPLOYPATH/*
      - echo "[INFO] Initiate Deployment to $DEPLOY_PATH..."
      - /bin/cp -Rf $PWD $DEPLOYPATH/